// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_jcm_g3_eixo_4_2025_1.Models;

#nullable disable

namespace Projeto_jcm_g3_eixo_4_2025_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250321153612_M00")]
    partial class M00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_jcm_g3_eixo_4_2025_1.Models.Alimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CachorroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Medida")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CachorroId");

                    b.ToTable("Alimentações");
                });

            modelBuilder.Entity("Projeto_jcm_g3_eixo_4_2025_1.Models.Cachorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nascimento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cachorros");
                });

            modelBuilder.Entity("Projeto_jcm_g3_eixo_4_2025_1.Models.Alimentacao", b =>
                {
                    b.HasOne("Projeto_jcm_g3_eixo_4_2025_1.Models.Cachorro", "Cachorro")
                        .WithMany("Alimentacoes")
                        .HasForeignKey("CachorroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cachorro");
                });

            modelBuilder.Entity("Projeto_jcm_g3_eixo_4_2025_1.Models.Cachorro", b =>
                {
                    b.Navigation("Alimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
